services:
  - type: web
    name: unimap-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app -c gunicorn_config.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
